# Generated by Django 5.1.4 on 2024-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnasiapp1', '0002_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('county', models.CharField(max_length=100)),
            ],
        ),
    ]
