# Generated by Django 5.1.4 on 2024-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnasiapp1', '0004_alter_county_county_alter_county_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Machakos', 'Machakos'), ('Meru', 'Meru'), ('Kiambu', 'Kiambu'), ('Nyeri', 'Nyeri'), ('Kajiado', 'Kajiado'), ('Narok', 'Narok'), ('Nyandarua', 'Nyandarua'), ('Laikipia', 'Laikipia'), ('Bomet', 'Bomet'), ('Kericho', 'Kericho'), ('Uasin Gishu', 'Uasin Gishu'), ('Bungoma', 'Bungoma'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Isiolo'), ('Samburu', 'Samburu'), ('Turkana', 'Turkana'), ('Wajir', 'Wajir'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Makueni', 'Makueni'), ('Embu', 'Embu'), ('Kitui', 'Kitui')], max_length=100),
        ),
    ]
